server:
  port: 8082
spring:
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://localhost:8888
        registration:
          spring:
            provider: spring
            client-id: spring
            client-secret: password
            authorization-grant-type:
            client-authentication-method: client_secret_basic
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: user.read, openid
