spring:
#  security:
#    oauth2:
#      authorizationserver:
#        client:
#          crm-client:
#            require-authorization-consent: true
#            registration:
#              client-id: crm
#              client-secret: "{bcrypt}$2a$14$QjNlaWdhx/1EXzdr0d4lDe2L06FLvIL/Z.NMs1ERbJ/0xnHBGKm5a"
#              authorization-grant-types:
#                - authorization_code
#                - refresh_token
#                - client_credentials
#              redirect-uris:
#                - http://127.0.0.1:8080/login/oauth2/code/spring
#              scopes: user.read, user.write, openid
#              client-authentication-methods:
#                - client_secret_basic
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-server
    username: postgres
    password: postgres
  sql:
    init:
      mode: always