spring:
  application:
    name: AUTHORIZATION-SERVER
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-server
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
jwt:
  key:
    id: hidetora
    private: classpath:/certs/app.key # should be stored in something like volt
    public: classpath:/certs/app.pub
jwk:
  persistence:
    password: password
    salt: 746F702D736563726574
server:
  port: 8888
springdoc:
  swagger-ui:
    path: /index.html
    oauth:
      realm: localhost:8888
